### ISSUE TITLE
How do you take book notes?

### ISSUE THREAD

**Issue by mloskot** [mgp/book-notes#10]
First, big cheers for the book notes project. It's a mine of knowledge.

Could you tell how do you take the notes?

Do you automate it, use Kindle highlights, an Android app, whatever, then export to Markdown?

**Comment by mgp** [comment]
On my Macbook, I have the Kindle app open with the book, as well as the markdown file open in a text editor (usually Sublime Text or MacVim, but it doesn't matter). When I read something that I want to summarize, I mentally commit it to memory and Command-Tab over to the text editor and type it out in Markdown. I don't copy-and-paste, because I find this solution allows me to retain the information better, and also it allows me to restructure the sentence if needed (usually editing for length). Usually my memory is not good enough and I Command-Tab back and forth, re-reading it in the Kindle app, and then re-reading what I typed out.

No highlights or any fancy exporting. Sorry if that's anti-climactic 😬 

For some of the older notes, I had the text editor open on my laptop, and then the physical book between me and my Macbook. But the algorithm was very similar 😛

**Comment by mloskot** [comment]
Excellent. Thank you :)
